lexik_jwt_authentication:
    secret_key: '%env(resolve:JWT_SECRET_KEY)%'
    public_key: '%env(resolve:JWT_PUBLIC_KEY)%'
    pass_phrase: '%env(JWT_PASSPHRASE)%'
    # Tempo de Duração Token
    token_ttl: 43200 # Default 3600
    # Campo de validação Token
    user_identity_field: email
