# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    locale: 'pt_BR'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # overload kernel exception
    #    App\Application\Project\ContentBundle\EventListener\ExceptionListener:
    #        tags:
    #            - { name: kernel.event_listener, event: kernel.exception }

    #    App\Application\Project\SecurityProviderApiBundle\EventListener\ExceptionListener:
    #        tags:
    #            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }
    #
    #


    # ####################################################################################
    # injeções de dependências

    #    app.menu_listener:
    #        class: App\Application\Project\ContentBundle\EventListener\MenuBuilderListener
    #        tags:
    #            - { name: kernel.event_listener, event: sonata.admin.event.configure.menu.sidebar, method: addMenuItems }
    #        arguments:


    #    admin.custom:
    #        class: App\Admin\CustomAdmin
    #        tags:
    #            - { name: sonata.admin, model_class: App\Entity\Custom, manager_type: orm, label: Category, security_handler: App\Application\Project\AdminBundle\Security\Handler }


    # ####################################################################################
    # serviços padrões da estrutura do projeto

    # Content Bundle
    project.content.content:
        class: App\Application\Project\ContentBundle\Admin\ContentAdmin
        tags:
            - {
                name: sonata.admin,
                manager_type: orm,
                model_class: App\Application\Project\ContentBundle\Entity\Content,
                controller: App\Application\Project\ContentBundle\Controller\ContentAdminController,
                show_in_dashboard: false,
                on_top: false,
                group: "Content",
                label: Content,
                icon: 'fa fa-solid fa-passport',
            }
            #- { name: sonata.admin, manager_type: orm, group: "Content", label: User, on_top: false, icon: 'fa fa-solid fa-user',, show_in_dashboard: false }

    project.content.setting:
        class: App\Application\Project\SettingBundle\Admin\SmtpEmailAdmin
        tags:
            - {
                name: sonata.admin,
                manager_type: orm,
                model_class: App\Application\Project\SettingBundle\Entity\SmtpEmail,
                controller: App\Application\Project\SettingBundle\Controller\SmtpEmailAdminController,
                show_in_dashboard: true,
                on_top: false,
                group: "Configurações",
                label: SMTP,
                icon: 'fas fa-cogs',
            }
            #- { name: sonata.admin, manager_type: orm, group: "Content", label: User, on_top: false, icon: 'fa fa-solid fa-user',, show_in_dashboard: false }






    # ####################################################################################
    # Provedor de usuário ADMIN

    project.security.provider.admin.user:
        class: App\Application\Project\SecurityAdminBundle\Admin\UserAdminAdmin
        calls:
        tags:
            - {
                name: sonata.admin,
                manager_type: orm,
                model_class: App\Application\Project\SecurityAdminBundle\Entity\UserAdmin,
                controller: App\Application\Project\SecurityAdminBundle\Controller\UserAdminAdminController,
                show_in_dashboard: true,
                on_top: false,
                group: "Acesso Admin",
                label: Administradores,
                icon: 'fa fa-solid fa-shield-alt',
            }

    project.security.provider.admin.group:
        class: App\Application\Project\SecurityAdminBundle\Admin\GroupAdminAdmin
        calls:
        tags:
            - {
                name: sonata.admin,
                manager_type: orm,
                model_class: App\Application\Project\SecurityAdminBundle\Entity\GroupAdmin,
                controller: App\Application\Project\SecurityAdminBundle\Controller\GroupAdminAdminController,
                show_in_dashboard: true,
                on_top: false,
                group: "Acesso Admin",
                label: Grupos,
                icon: 'fa fa-solid fa-shield-alt',
            }

    # ####################################################################################
    # Provedor de usuário API

    project.security.provider.api.user:
        class: App\Application\Project\SecurityUserBundle\Admin\UserAdmin
        tags:
            - {
                name: sonata.admin,
                manager_type: orm,
                model_class: App\Application\Project\SecurityUserBundle\Entity\User,
                controller: App\Application\Project\SecurityUserBundle\Controller\UserAdminController,
                show_in_dashboard: true,
                on_top: false,
                group: "Acesso Usuários",
                label: Usuários,
                icon: 'fa fa-solid fa-users',
            }

    project.security.provider.api.group:
        class: App\Application\Project\SecurityUserBundle\Admin\GroupAdmin
        tags:
            - {
                name: sonata.admin,
                manager_type: orm,
                model_class: App\Application\Project\SecurityUserBundle\Entity\Group,
                controller: App\Application\Project\SecurityUserBundle\Controller\GroupAdminController,
                show_in_dashboard: true,
                on_top: false,
                group: "Acesso Usuários",
                label: Grupos,
                icon: 'fa fa-solid fa-users',
            }

    # ####################################################################################
    # por favor, note que as últimas definições sao da estrutura padrão do projeto
    # adicione mais definições de serviço quando for necessária abaixo


    # Services Schemas Bundle
    # ####################################################################################
    internit.cursobundle.curso:
        class: App\Application\Internit\CursoBundle\Admin\CursoAdmin
        tags:
            - {
                name: sonata.admin,
                manager_type: orm,
                model_class: App\Application\Internit\CursoBundle\Entity\Curso,
                controller: App\Application\Internit\CursoBundle\Controller\CursoAdminController,
                show_in_dashboard: true,
                on_top: true,
                group: "Curso",
                label: Curso,
                icon: 'fa fa-solid fa-book',
            }

    internit.tipocursobundle.tipocurso:
        class: App\Application\Internit\TipoCursoBundle\Admin\TipoCursoAdmin
        tags:
            - {
                name: sonata.admin,
                manager_type: orm,
                model_class: App\Application\Internit\TipoCursoBundle\Entity\TipoCurso,
                controller: App\Application\Internit\TipoCursoBundle\Controller\TipoCursoAdminController,
                show_in_dashboard: true,
                on_top: true,
                group: "TipoCurso",
                label: TipoCurso,
                icon: 'fa fa-solid fa-book',
            }

    internit.regimebundle.regime:
        class: App\Application\Internit\RegimeBundle\Admin\RegimeAdmin
        tags:
            - {
                name: sonata.admin,
                manager_type: orm,
                model_class: App\Application\Internit\RegimeBundle\Entity\Regime,
                controller: App\Application\Internit\RegimeBundle\Controller\RegimeAdminController,
                show_in_dashboard: true,
                on_top: true,
                group: "Regime",
                label: Regime,
                icon: 'fa fa-solid fa-book',
            }

    internit.alunobundle.aluno:
        class: App\Application\Internit\AlunoBundle\Admin\AlunoAdmin
        tags:
            - {
                name: sonata.admin,
                manager_type: orm,
                model_class: App\Application\Internit\AlunoBundle\Entity\Aluno,
                controller: App\Application\Internit\AlunoBundle\Controller\AlunoAdminController,
                show_in_dashboard: true,
                on_top: true,
                group: "Aluno",
                label: Aluno,
                icon: 'fa fa-solid fa-book',
            }

    internit.documentoacademicobundle.documentoacademico:
        class: App\Application\Internit\DocumentoAcademicoBundle\Admin\DocumentoAcademicoAdmin
        tags:
            - {
                name: sonata.admin,
                manager_type: orm,
                model_class: App\Application\Internit\DocumentoAcademicoBundle\Entity\DocumentoAcademico,
                controller: App\Application\Internit\DocumentoAcademicoBundle\Controller\DocumentoAcademicoAdminController,
                show_in_dashboard: true,
                on_top: true,
                group: "DocumentoAcademico",
                label: DocumentoAcademico,
                icon: 'fa fa-solid fa-book',
            }

    internit.tipotrabalhobundle.tipotrabalho:
        class: App\Application\Internit\TipoTrabalhoBundle\Admin\TipoTrabalhoAdmin
        tags:
            - {
                name: sonata.admin,
                manager_type: orm,
                model_class: App\Application\Internit\TipoTrabalhoBundle\Entity\TipoTrabalho,
                controller: App\Application\Internit\TipoTrabalhoBundle\Controller\TipoTrabalhoAdminController,
                show_in_dashboard: true,
                on_top: true,
                group: "TipoTrabalho",
                label: TipoTrabalho,
                icon: 'fa fa-solid fa-book',
            }

    internit.palavrachavebundle.palavrachave:
        class: App\Application\Internit\PalavraChaveBundle\Admin\PalavraChaveAdmin
        tags:
            - {
                name: sonata.admin,
                manager_type: orm,
                model_class: App\Application\Internit\PalavraChaveBundle\Entity\PalavraChave,
                controller: App\Application\Internit\PalavraChaveBundle\Controller\PalavraChaveAdminController,
                show_in_dashboard: true,
                on_top: true,
                group: "PalavraChave",
                label: PalavraChave,
                icon: 'fa fa-solid fa-book',
            }

    internit.corpoacademicobundle.corpoacademico:
        class: App\Application\Internit\CorpoAcademicoBundle\Admin\CorpoAcademicoAdmin
        tags:
            - {
                name: sonata.admin,
                manager_type: orm,
                model_class: App\Application\Internit\CorpoAcademicoBundle\Entity\CorpoAcademico,
                controller: App\Application\Internit\CorpoAcademicoBundle\Controller\CorpoAcademicoAdminController,
                show_in_dashboard: true,
                on_top: true,
                group: "CorpoAcademico",
                label: CorpoAcademico,
                icon: 'fa fa-solid fa-book',
            }

    internit.titulobundle.titulo:
        class: App\Application\Internit\TituloBundle\Admin\TituloAdmin
        tags:
            - {
                name: sonata.admin,
                manager_type: orm,
                model_class: App\Application\Internit\TituloBundle\Entity\Titulo,
                controller: App\Application\Internit\TituloBundle\Controller\TituloAdminController,
                show_in_dashboard: true,
                on_top: true,
                group: "Titulo",
                label: Titulo,
                icon: 'fa fa-solid fa-book',
            }

    internit.tipotitulobundle.tipotitulo:
        class: App\Application\Internit\TipoTituloBundle\Admin\TipoTituloAdmin
        tags:
            - {
                name: sonata.admin,
                manager_type: orm,
                model_class: App\Application\Internit\TipoTituloBundle\Entity\TipoTitulo,
                controller: App\Application\Internit\TipoTituloBundle\Controller\TipoTituloAdminController,
                show_in_dashboard: true,
                on_top: true,
                group: "TipoTitulo",
                label: TipoTitulo,
                icon: 'fa fa-solid fa-book',
            }

